name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ main ]


env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  ALIYUN_NAME_SPACE: "${{ secrets.ALIYUN_NAME_SPACE }}"

jobs:

  build:
    name: Pull
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Aliyun
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.ALIYUN_REGISTRY }}
        username: ${{ secrets.ALIYUN_REGISTRY_USER }}
        password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

    - name: Check out code
      uses: actions/checkout@v4

    - name: Build and push image Aliyun
      run: |
        while IFS="" read -r line || [ -n "$line" ]
        do
          count="${line//[^\/]}"
          case ${#count} in
            0) # image name contains no slash (e.g official image)
              prefix=""
              author=""
              image_name=${line}
              ;;
            1) # image name contains a slash (e.g. jellyfin/jellyfin)
              prefix=""
              author="${line%/*}_"
              image_name=${line#*/}
              ;;
            2) # image name contains two slashes (e.g. download from other repository)
              prefix="${line%%/*}_"
              name_components=${line#*/}
              author="${name_components%/*}_"
              image_name=${name_components#*/}
              ;;
          esac
          if [[ $image_name == *":"* ]]; then
            tag_name=${image_name#*:}
            image_name=${image_name%:*}
          else
            tag_name="latest"
          fi
          new_image_name="$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/${image_name}:${prefix}${author}${tag_name}"
          echo "docker pull $line"
          docker pull $line
          echo "docker tag $line $new_image_name"
          docker tag $line $new_image_name
          echo "docker push $new_image_name"
          docker push $new_image_name
        done < images.txt
